### ISSUE TITLE
environment configuration

### ISSUE THREAD

**Issue by MultimodalAttentionFusion** [JulFrey/DetailView#1]
Can you provide us with a description of how to install the PDAL? My PDAL and Pytorch environments cannot be installed into one environment, can you provide detailed environment configuration?

**Comment by JulFrey** [comment]
I am running this in a conda environment with python version 3.10.10. Attached you'll find a txt file with all the packages and their versions installed.
[environment.txt](https://github.com/JulFrey/DetailView/files/13986198/environment.txt)

**Comment by MultimodalAttentionFusion** [comment]
Thanks for the answer

> I am running this in a conda environment with python version 3.10.10. Attached you'll find a txt file with all the packages and their versions installed. [environment.txt](https://github.com/JulFrey/DetailView/files/13986198/environment.txt)

Thanks for the answer

**Comment by MultimodalAttentionFusion** [comment]
Can you provide tree_metadata_training_publish.csv files? There is always a problem with the files that I construct myself

**Comment by MultimodalAttentionFusion** [comment]
This is great, thank you

**Comment by MultimodalAttentionFusion** [comment]
When I ran downsampling.py, the following error occurred. Have you encountered it? How to solve it?
RuntimeError Traceback (most recent call last)
Cell In[1], line 95
91 # execution for all training las files
92 for path_curr in glob.glob(os.path.join(path_las, "*.las")):
93
94 # downsample & get height
---> 95 path_sub, height = downsample(path_curr, path_out, min_n = 1, get_height = True)
97 # change path
98 lowest_folder = os.path.basename(os.path.dirname(path_sub))

Cell In[1], line 59
57 if get_height:
58 pipeline = pdal.Pipeline([las_reader])
---> 59 pipeline.execute()
60 height = pipeline.arrays[0]["Z"].max() - pipeline.arrays[0]["Z"].min()
61 else:

RuntimeError: Can't create dimension with invalid name '_Amplitude'.
