### ISSUE TITLE
Structure of tree_metadata_training_publish.csv file

### ISSUE THREAD

**Issue by JulFrey** [JulFrey/DetailView#2]
Can you provide tree_metadata_training_publish.csv files? There is always a problem with the files that I construct myself

_Originally posted by @luogkr in https://github.com/JulFrey/DetailView/issues/1#issuecomment-1966795691_

**Comment by JulFrey** [comment]
I can't since the dataset is not yet published, but the structure looks like this:

treeID,species,genus,dataset,data_type,tree_H,filename
70,Eucalyptus_miniata,Eucalyptus,DS1,TLS,9.01,/train/00070.las
71,Eucalyptus_miniata,Eucalyptus,DS1,TLS,7.84,/train/00071.las
72,Eucalyptus_miniata,Eucalyptus,DS1,TLS,14.89,/train/00072.las
73,Eucalyptus_miniata,Eucalyptus,DS1,TLS,18.73,/train/00073.las
74,Eucalyptus_miniata,Eucalyptus,DS1,TLS,6.49,/train/00074.las
76,Eucalyptus_miniata,Eucalyptus,DS1,TLS,9.02,/train/00076.las
78,Eucalyptus_miniata,Eucalyptus,DS1,TLS,10.11,/train/00078.las

**Comment by MultimodalAttentionFusion** [comment]
When I ran downsampling.py, the following error occurred. Have you encountered it? How to solve it?
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 95
     91 # execution for all training las files
     92 for path_curr in glob.glob(os.path.join(path_las, "*.las")):
     93     
     94     # downsample & get height
---> 95     path_sub, height = downsample(path_curr, path_out, min_n = 1, get_height = True)
     97     # change path
     98     lowest_folder = os.path.basename(os.path.dirname(path_sub))

Cell In[1], line 59
     57 if get_height:
     58     pipeline = pdal.Pipeline([las_reader])
---> 59     pipeline.execute()
     60     height = pipeline.arrays[0]["Z"].max() - pipeline.arrays[0]["Z"].min()
     61 else:

RuntimeError: Can't create dimension with invalid name '_Amplitude'.
