### ISSUE TITLE
Can't create dimension with invalid name '_Amplitude'.

### ISSUE THREAD

**Issue by MultimodalAttentionFusion** [JulFrey/DetailView#3]
When I ran downsampling.py, the following error occurred. Have you encountered it? How to solve it?
RuntimeError Traceback (most recent call last)
Cell In[1], line 95
91 # execution for all training las files
92 for path_curr in glob.glob(os.path.join(path_las, "*.las")):
93
94 # downsample & get height
---> 95 path_sub, height = downsample(path_curr, path_out, min_n = 1, get_height = True)
97 # change path
98 lowest_folder = os.path.basename(os.path.dirname(path_sub))

Cell In[1], line 59
57 if get_height:
58 pipeline = pdal.Pipeline([las_reader])
---> 59 pipeline.execute()
60 height = pipeline.arrays[0]["Z"].max() - pipeline.arrays[0]["Z"].min()
61 else:

RuntimeError: Can't create dimension with invalid name '_Amplitude'.

**Comment by JulFrey** [comment]
I can't tell for sure what the reason for this error is, but it looks like you have an attribute within your las-file named _Amplitude, which is invalid within the las standard.
